name: Build

on:
  push:
    branches: [ "main", "hotfix" ]
    paths:
      - "src/telem"
  pull_request:
    branches: [ "main", "hotfix" ]
    paths:
      - "src/telem"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.3"

      - uses: leafo/gh-actions-luarocks@v4
      
      - name: Install luacc
        run: luarocks install luacc
      
      - name: Install luamin
        run: sudo yarn global add https://github.com/cyberbit/luamin

      - name: Build
        run: ./src/telem/build.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modules-flat
          path: dist/modules/*.lua
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modules-luz
          path: dist/modules/*.luz
      
      # via https://github.com/softprops/action-gh-release/issues/270
      - name: Tag
        id: tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          TAG=v0.0.0+$(date -Iseconds | sed 's/[-T:\+]//g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          prerelease: true
          draft: true
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            dist/modules/*.lua
            dist/modules/*.luz
